<?php
/**
 * Bootstrap Genesis Plugin.
 *
 * WARNING: This file is part of the core Bootstrap Genesis Plugin. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package BootstrapGenesis\Header
 * @author  BryanWillis
 * @license GPL-2.0+
 * @link    https://github.com/Wordpress-Development/genesis-bootstrap/
 */


add_filter( 'language_attributes', 'bsg_js_detection_lang_atts' );
add_action( 'genesis_doctype', 'bsg_js_detection_script', 100 );
/**
 * Add `no-js` class to `<html>` and include javascript check script early
 * 
 * @link http://www.paulirish.com/2009/avoiding-the-fouc-v3/
 * 
 * @since 1.0.0
 */
function bsg_js_detection_lang_atts($output) {
	return $output . ' class="no-js"';
}
function bsg_js_detection_script() {
	if ( has_filter( 'language_attributes', 'bsg_js_detection_lang_atts' ) ) {
		echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n";
		
	}
}


add_action( 'send_headers', 'bsg_add_header_xua_compatible' );
/**
 * Add `X-UA-compatible` meta tag using send_headers to ensure it's being used by IE9 Intranets and avoid validation errors
 * 
 * @since 1.0.0
 */
function bsg_add_header_xua_compatible() {
	header( 'X-UA-Compatible: IE=edge,chrome=1' );
}





remove_action( 'wp_head', 'genesis_html5_ie_fix' ); 
add_action('wp_print_scripts', function() {
    global $wp_scripts, $is_IE;
    if($is_IE) {
        wp_enqueue_script( 'html5shiv', 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', array( 'bootstrap' )  );
        wp_enqueue_script( 'respond', 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js', array( 'bootstrap' )  );
        $wp_scripts->add_data( 'html5shiv', 'conditional', 'lt IE 9' );
        $wp_scripts->add_data( 'respond', 'conditional', 'lt IE 9' );
    }
} );





remove_action( 'genesis_meta', 'genesis_responsive_viewport' );
// Add viewport earlier for better rendering
add_action( 'genesis_doctype', function() {
	return bsg_genesis_responsive_viewport( );
});
function bsg_genesis_responsive_viewport( ) {
	if ( ! current_theme_supports( 'genesis-responsive-viewport' ) )
		return;
	$content = apply_filters('genesis_responsive_viewport', 'width=device-width, initial-scale=1');
	echo '<meta name="viewport" content="'.$content.'" />' . "\n";
}

/*
add_filter('genesis_responsive_viewport', function(){
    return 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no';
} );
// */
