<?php

/**
 * Bootstrap Genesis Plugin.
 *
 * WARNING: This file is part of the core Bootstrap Genesis Plugin. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package BootstrapGenesis\Header
 * @author  BryanWillis
 * @license GPL-2.0+
 * @link    https://github.com/Wordpress-Development/genesis-bootstrap/
 */



add_filter( 'language_attributes', 'bsg_js_detection_lang_atts' );
add_action( 'genesis_doctype', 'bsg_js_detection_script', 100 );
/**
 * Add `no-js` class to `<html>` and include javascript check script early
 * 
 * @link http://www.paulirish.com/2009/avoiding-the-fouc-v3/
 * 
 * @since 1.0.0
 */
function bsg_js_detection_lang_atts($output) {
	return $output . ' class="no-js"';
}
function bsg_js_detection_script() {
	if ( has_filter( 'language_attributes', 'bsg_js_detection_lang_atts' ) ) {
		echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n";
		
	}
}



add_action( 'send_headers', 'bsg_add_header_xua_compatible' );
/**
 * Add `X-UA-compatible` meta tag using send_headers to ensure it's being used by IE9 Intranets and avoid validation errors
 * 
 * @since 1.0.0
 */
function bsg_add_header_xua_compatible() {
	header( 'X-UA-Compatible: IE=edge,chrome=1' );
}



remove_action( 'wp_head', 'genesis_html5_ie_fix' ); 
add_action( 'wp_head', 'bsg_html5_shiv_respond_js_add_last', 999 );
/**
 * HTML5shiv tag support for HTML5 and Respond.js for IE8 media queries
 * 
 * @link http://getbootstrap.com/getting-started/#support-ie8-ie9
 * 
 * @since 1.0.0
 */
function bsg_html5_shiv_respond_js_add_last() {	
?><!--[if lt IE 9]>
<script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<?php
}



remove_action( 'genesis_meta', 'genesis_responsive_viewport' );
add_action('genesis_setup','bootstrap_genesis_responsive_viewport', 15);
/**
 * Add genesis responsive viewport if it's not explicitly removed using `remove_theme_support('genesis-responsive-viewport');` in child theme.
 * 
 * @since 1.0.0
 */
function bootstrap_genesis_responsive_viewport() {
	if ( genesis_html5()  && ! current_theme_supports( 'genesis-responsive-viewport' ) ) {
		add_theme_support('genesis-responsive-viewport');
	}
}
